version: '2.1'
services:
  postgres-db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_PASSWORD: Bl0ckuD0kuAdm1n
      POSTGRES_USER: db-admin
      POSTGRES_DB: blockudoku
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - '5432'
    ports: 
      - 6543:5432